[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0x46db9761af921b932ec1aa8750177e8f310c9c4c49a8e19748c5a72db3edbc8c'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]